### ISSUE TITLE
Adding WordCounter project to the repository. [Hacktoberfest]

### ISSUE THREAD

**Issue by thevirengarg** [VidhiBhatt01/The-Frontend-Store#105]
Adding a front end project to the repo, which calculates typing speed of the user and helps in practicing speed typing.
This website is created using HTML, CSS, javascript.
@VidhiBhatt01 Please assign this issue to me.

![Screenshot (287)](https://github.com/VidhiBhatt01/The-Frontend-Store/assets/111726483/0775dd5b-9abc-48ff-a39d-adc19bf30a0b)

![Screenshot (289)](https://github.com/VidhiBhatt01/The-Frontend-Store/assets/111726483/edb20ce5-c8bf-4776-b4c0-1f276595b967)

![Screenshot (288)](https://github.com/VidhiBhatt01/The-Frontend-Store/assets/111726483/7b6447e4-d2ed-49c4-a103-d2d5890534cb)

**Comment by thevirengarg** [comment]
@VidhiBhatt01 Please assign me this issue

**Comment by VidhiBhatt01** [comment]
Closed with #112
