### ISSUE TITLE
Adding Code of Conduct

### ISSUE THREAD

**Issue by hiferli** [VidhiBhatt01/The-Frontend-Store#11]
Can I add a Code of Conduct to this repository?
Please assign this issue to me so that I can work on the same.

**Comment by VidhiBhatt01** [comment]
What all will you include? please elaborate a little

**Comment by hiferli** [comment]
A Code of Conduct includes the following things:
- Guidelines for open source contribution 
- Acceptable and Unacceptable Behavior 
- Enforcement Responsibility 
- Enforcement Guidelines
- Scope of the Conduct 
- Actions
  - Corrections
  - Warnings
  - Temporary Ban
  - Permanent Ban
- Attributions and Important References

**Comment by hiferli** [comment]
If you need anything else apart from this then please let me know

**Comment by VidhiBhatt01** [comment]
Sounds good!

**Comment by hiferli** [comment]
Made the PR.
Please check and let me know about the same :)
