### ISSUE TITLE
Drag and Drop Sortable List Using JavaScript

### ISSUE THREAD

**Issue by Robinrai2612** [VidhiBhatt01/The-Frontend-Store#111]
## Description:

I will create a drag-and-drop sortable list using HTML, CSS, and JavaScript.
To create a drag-and-drop sortable list, I will use the following steps:

*  Create an HTML list element. Each list item should have a unique id attribute.
* Add the draggable attribute to each list item.
* Add CSS styles to the list element and list items to control their appearance.
* Write JavaScript code to handle the drag and drop events.
* Update the order of the list items when they are dropped.

@VidhiBhatt01 I would like to work on this issue. Please assign it to me.

@VidhiBhatt01 Please add me in the contributors list of this repository.

**Comment by VidhiBhatt01** [comment]
Assigned, you would be automatically added to the list when your PR is merged
