### ISSUE TITLE
Add more projects and more games

### ISSUE THREAD

**Issue by Samadeen** [VidhiBhatt01/The-Frontend-Store#15]
I would like to add a reusable Testimonial slider / Image slider and a typing game, catch-the-insect game

**Comment by VidhiBhatt01** [comment]
Go on, make different PRs for different projects

**Comment by JayantDane123** [comment]
Hello sir ,
please assign me for this  
I ensure to complete it

**Comment by Samadeen** [comment]
Done them

**Comment by rjrishika** [comment]
i would like to add recipe app,drawing app, snake game and github application using github apii

**Comment by VidhiBhatt01** [comment]
@rjrishika this issue is already assigned to samadeen. If you want to add projects, raise a new issue for yourself

**Comment by Samadeen** [comment]
I'm still trying to perfect them... Before creating PRs

**Comment by VidhiBhatt01** [comment]
Hey @Samadeen, are you still working on this issue? If not, kindly close the issue...

**Comment by Samadeen** [comment]
Hello @VidhiBhatt01 ... I plan on adding two more projects. I've been busy with stuff and I'll finish up soon.

**Comment by VidhiBhatt01** [comment]
Cool
