### ISSUE TITLE
An uber cloned app

### ISSUE THREAD

**Issue by DiamonndAde** [VidhiBhatt01/The-Frontend-Store#45]
Can I make an uber clone app?

**Comment by VidhiBhatt01** [comment]
Sure, go on! What all tech stacks will you use?

**Comment by DiamonndAde** [comment]
nextJS, html and css

**Comment by VidhiBhatt01** [comment]
If possible, please only use Vanilla JS as projects with other JS frameworks might not get deployed as of now by the bot.

Incase you decide to go with NextJS, please attach a link where you have published the clone so that I can verify

**Comment by DiamonndAde** [comment]
Alright
