### ISSUE TITLE
TIC TAC TOC GAME

### ISSUE THREAD

**Issue by ishikagoyal02** [VidhiBhatt01/The-Frontend-Store#71]
It is a simple and popular game using HTML, CSS and JAVASCRIPT

**Comment by VidhiBhatt01** [comment]
Please finish the issue ASAP

**Comment by manthankhawse** [comment]
hello @VidhiBhatt01
Can you please assign this issue to me?

**Comment by VidhiBhatt01** [comment]
It's completed now. You can add any other project of yours @manthankhawse
