### ISSUE TITLE
Myntra Clone

### ISSUE THREAD

**Issue by ishikagoyal02** [VidhiBhatt01/The-Frontend-Store#75]
Building a responsive and famous website for shopping

**Comment by VidhiBhatt01** [comment]
You have opened so many issues, I hope you will contribute genuinely and not just copy-paste stuff.

**Comment by ABHINAV2087** [comment]
hello @VidhiBhatt01 , please assign this to me ...

**Comment by VidhiBhatt01** [comment]
@ABHINAV2087 any updates on this?

**Comment by ABHINAV2087** [comment]
mam you have already merged a pr related to this https://github.com/VidhiBhatt01/The-Frontend-Store/tree/main/Clones/myntra-clone  here you can check  kindly have a look
